---
# The variables are separated out to make it easier to update.

opensuse:
  # Docker URL and version
  name: leap
  url: "docker.io/opensuse/leap"
  version: "16.0"

published:
  # The openSUSE name and version are appended: v0.1.1-leap-15.6
  version: "v1.3.1"
  base:
    # Published image name and version
    name: "opensuse-base"
  dev:
    # Published image name and version
    name: "opensuse-dev"

packages:
  # TODO: Dynamically add the base list to the dev list.
  base:
    # The user inside the container is "dev"
    - sudo
    # Basic utils
    - vim
    - vim-data
    - git
    - tar
    - gzip
    - bzip2
    - zip
    - unzip
    - zstd
    - which
    # Required for Forgejo actions
    - nodejs-common
    - nodejs24
    - openssh-clients
    # Container tools
    - buildah
    - docker
    - docker-compose
    - docker-buildx
    - fuse-overlayfs
  dev:
    # The user inside the container is "dev"
    - sudo
    # Basic utils
    - vim
    - vim-data
    - git
    - tar
    - gzip
    - bzip2
    - unzip
    - zstd
    - which
    # Required for Forgejo actions
    - nodejs-common
    - openssh-clients
    # Container tools
    - buildah
    - docker
    - docker-compose
    - docker-buildx
    - fuse-overlayfs
    # Needed for remote development with JetBrains
    - java-21-openjdk-devel
    # PostgreSQL is preferred db for development
    - postgresql17
    # Development
    - clang
    - libopenssl-devel
    - gcc
    # pattern: devel_basis
    - bison
    - flex
    - gdbm-devel
    - libfl-devel
    - libfl2
    - libtool
    - makeinfo
    - patch
    - patterns-devel-base-devel_basis
    - perl-Text-Unidecode
    # Dioxus
    - webkit2gtk3-devel
    - libopenssl-devel
    - libappindicator3-1
    - librsvg-devel

bun:
  # TODO: Dynamically add the base list to the dev list.
  base:
    - prettier
    - cspell
    # Needed for yarn
    - corepack
  dev:
    - prettier
    - cspell
    # Needed for yarn
    - corepack
    - '@anthropic-ai/claude-code'
    - '@tailwindcss/cli'

uv:
  # Dynamically add the base list to the dev list.
  base:
    - yamllint
  dev:
    - yamllint

rust:
  # https://github.com/rust-lang/rust/releases
  # Note: Rust has a 6-week release cycle and only the latest stable version is officially supported.
  # There's no long-term support (LTS) model.
  # Possible value: stable
  version: "1.94"

binaries:
  host: dufs.niceguyit.biz
  list:
    - name: age
      version: "v1.3.1"
    - name: btm
      version: "0.10.2"
    - name: bun
      version: "v1.3"
    - name: chezmoi
      version: "v2.70.2"
    - name: doggo
      version: "v1.1.5"
    # Dioxus
    - name: dx
      version: "v0.7.7"
    - name: fd
      version: "v10.4.2"
    - name: gh
      version: "2.41.0"
    - name: just
      version: "1.50.0"
    - name: kingfisher
      version: "1.59.0"
    - name: nebula
      version: "v1.10.3"
    - name: noseyparker
      version: "v0.24.0"
    - name: nu
      version: "0.112.2"
    - name: nu
      version: "0.112.2"
      file: nu_plugin_formats
    - name: nu
      version: "0.112.2"
      file: nu_plugin_gstat
    - name: nu
      version: "0.112.2"
      file: nu_plugin_inc
    - name: nu
      version: "0.112.2"
      file: nu_plugin_polars
    - name: ouch
      version: "0.7.1"
    - name: pinger
      version: "v1.3.1"
    - name: rage
      version: "v0.11.2"
    - name: rg
      version: "14.0.3"
    - name: rclone
      version: "v1.74.0"
    - name: starship
      version: "v1.25.1"
    - name: trufflehog
      version: "v3.95.2"
    - name: uv
      version: "0.9.21"
    - name: uv
      version: "0.9.21"
      file: uvx

dotfiles:
  repo: https://github.com/NiceGuyIT/dotfiles.git
