---
# The variables are separated out to make it easier to update.

opensuse_leap:
  # Docker URL and version
  url: "docker.io/opensuse/leap"
  version: "15.6"

published:
  # Published image name and version
  name: "opensuse_leap"
  version: "v15.6-20250919"
