---
# Build rust-builder images and push to GHCR.
name: Build rust-builder container

on:
  push:
    branches: [main]
    paths:
      - "rust-builder/**"
      - ".github/workflows/build-rust-builder.yml"
      - ".github/workflows/build-and-push-image.yml"

jobs:
  build-base:
    name: Build rust-builder base image
    uses: ./.github/workflows/build-and-push-image.yml
    permissions:
      contents: read
      packages: write
    with:
      image-name: rust-builder
      image-type: base

  build-dioxus:
    name: Build rust-builder dioxus image
    needs: build-base
    uses: ./.github/workflows/build-and-push-image.yml
    permissions:
      contents: read
      packages: write
    with:
      image-name: rust-builder
      image-type: dioxus

  build-dioxus-desktop:
    name: Build rust-builder dioxus-desktop image
    needs: build-dioxus
    uses: ./.github/workflows/build-and-push-image.yml
    permissions:
      contents: read
      packages: write
    with:
      image-name: rust-builder
      image-type: dioxus-desktop
