---
# Build rust-builder-musl image and push to GHCR.
name: Build rust-builder-musl container

on:
  push:
    branches: [main]
    paths:
      - "rust-builder-musl/**"
      - ".github/workflows/build-rust-builder-musl.yml"
      - ".github/workflows/build-and-push-image.yml"

jobs:
  build:
    name: Build rust-builder-musl image
    uses: ./.github/workflows/build-and-push-image.yml
    permissions:
      contents: read
      packages: write
    with:
      image-name: rust-builder-musl
